export const apiTableName = {
  profile: "profile" as "profile",
  customer: "customer" as "customer",
  passwordHistory: "passwordHistory" as "passwordHistory",
  customerLogin: "customerLogin" as "customerLogin",
  loginAttempHistory: "loginAttempHistory" as "loginAttempHistory",
  product: "product" as "product",
  productCategory: "productCategory" as "productCategory",
  pricingHistory: "pricingHistory" as "pricingHistory",
  relatedProduct: "relatedProduct" as "relatedProduct",
  productVendor: "productVendor" as "productVendor",
  orderStatusCode: "orderStatusCode" as "orderStatusCode",
  order: "order" as "order",
  orderItem: "orderItem" as "or derItem",
  orderItemReturn: "orderItemReturn" as "orderItemReturn",
  shoppingCartItem: "shoppingCartItem" as "shoppingCartItem",
  shoppingCartHistory: "shoppingCartHistory" as "shoppingCartHistory",
  shoppingCartHistoryAction:
    "shoppingCartHistoryAction" as "shoppingCartHistoryAction",
  shipment: "shipment" as "shipment",
  shipmentItem: "shipmentItem" as "shipmentItem",
};
